#!/bin/bash

# This is a thin wrapper around gcoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using gcoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_GCOIND

# Grab the value of $REAL_GCOINCLI which may be gcoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_GCOINCLI}" "$@" | sed 's/\r//'
